---
title: "HW4"
author: "Sarah Rohlfing"
date: '2022-05-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(janitor)
library(here)
# options(scipen = 99)
```

```{r}
## read in data
warming <- read.csv(here("data", "warming.csv")) %>% 
  clean_names() 

damages <- read.csv(here("data", "damages.csv")) %>% 
  clean_names() 
```


create a linear regregression for warming predicted line
```{r}
damages$warming2 <- damages$warming ^ 2

predicted.lm <- lm(damages ~ 0 + warming + warming2 -1, data = damages)

damages$seq_temp = seq(.1, 10, length.out = 556)

```

```{r}
pred_dam_fun <- function(x){predicted.lm$coefficients[1]*x + predicted.lm$coefficients[2]*x^2}

pulse <- 35000000000
ggplot(data = damages, aes(y = damages, x = warming)) +
  geom_jitter()+
  labs(x = "Temperature (C)",
       y = "Cost of Damages",
       title = "Cost of climate Change") +
stat_function(fun = pred_dam_fun, color = "red")
```

```{r}
warming <- warming %>% 
  mutate(pred_base = pred_dam_fun(x = warming_baseline)) %>% 
  mutate(pred_pulse = pred_dam_fun(x = warming_pulse)) %>% 
  mutate(diff_of_pulse = pred_pulse - pred_base) %>% 
  mutate(damage_per_ton = diff_of_pulse/pulse)
```


```{r}
ggplot(data = warming, aes(x = year, y = pred_base)) +
  geom_smooth() +
  labs(x = "year",
       y = "Damage ($)",
       title = "Baseline future damage predictions")

ggplot(data = warming, aes(x = year, y = pred_pulse)) +
  geom_smooth() +
  labs(x = "year",
       y = "Damage with pulse($)",
       title = "Future damage predictions with CO2 Pulse")

ggplot(data = warming, aes(x = year, y = diff_of_pulse)) +
  geom_smooth() +
  labs(x = "year",
       y = "Difference of damage ($)",
       title = "Difference in damage from baseline with added pulse")

ggplot(data = warming, aes(x = year, y = damage_per_ton)) +
  geom_smooth() +
  labs(x = "year",
       y = "Damage per ton of CO2($)",
       title = "Damage of pulse per ton of CO2")

```
#3
```{r}
SCC <- warming %>% 
  mutate(dr_01 = damage_per_ton/((1 + .01)^(year-2022))) %>% 
  mutate(dr_02 = damage_per_ton/((1 + .02)^(year-2022))) %>%
  mutate(dr_03 = damage_per_ton/((1 + .03)^(year-2022))) %>% 
  mutate(dr_04 = damage_per_ton/((1 + .04)^(year-2022))) %>%
  mutate(dr_05 = damage_per_ton/((1 + .05)^(year-2022))) %>% 
  mutate(dr_06 = damage_per_ton/((1 + .06)^(year-2022))) %>% 
  mutate(dr_07 = damage_per_ton/((1 + .07)^(year-2022))) %>%
  mutate(dr_08 = damage_per_ton/((1 + .08)^(year-2022))) %>% 
  mutate(dr_09 = damage_per_ton/((1 + .09)^(year-2022))) %>% 
  mutate(dr_1 = damage_per_ton/((1 + .1)^(year-2022)))


discount_rate <- c(1,2,3,4,5,6,7,8,9,10)
scc_sums <- c(sum(SCC$dr_01), sum(SCC$dr_02), sum(SCC$dr_03), sum(SCC$dr_04), sum(SCC$dr_05), sum(SCC$dr_06), sum(SCC$dr_07), sum(SCC$dr_08), sum(SCC$dr_09), sum(SCC$dr_1))

scc_data_frame <- data.frame(discount_rate, scc_sums)
```

```{r}
ggplot(data = scc_data_frame, aes(x = discount_rate, y = scc_sums)) +
 geom_point() +
  geom_line() +
  labs(x = "discount rate (%)", 
       y = "sum cost of carbon",
       title = "The total cost of carbon in 2100 with different discount rates")
```
```{r}

# r  = p + ng
# find r when p=.001, n= 2, and g = 0.01
rr <- .001 + 2 * .01 # = 0.021

SCC <- warming %>% 
  mutate(dr_rr = damage_per_ton/((1 + .021)^(year-2022))) 

dr_rr_sum <- c(sum(SCC$dr_rr)) # = 71.354

```
#5
```{r}
SCC <- SCC %>% 
  mutate(baseline_A_1.5 = pred_dam_fun(warming_baseline*1.5)) %>% 
  mutate(PV_A_1.5 = baseline_A_1.5/((1.02)^(year-2022))) %>% 
  mutate(PV_A_base = pred_base/((1.02)^(year-2022))) %>% 
  mutate(policy_B_temp = ifelse(year < 2050, warming_baseline, 1.29)) %>% 
  mutate(baseline_B = pred_dam_fun(policy_B_temp)) %>% 
  mutate(PV_B_base = baseline_B/((1.02)^(year-2022)))

policy_A_PV <- sum(SCC$PV_A_base)*.5 + sum(SCC$PV_A_1.5)*.5 # expected present value of damages under policy A
policy_B_PV <- sum(SCC$PV_B_base) # expected present value of damages under policy B
```

```{r}
imp_cost <- policy_A_PV - policy_B_PV # to get an estimate for cost

potential_cost <- c(0, 1e15, 2e15, 3e15, 4e15, 5e15, 6e15, 7e15, 8e15, 9e15)

cost.df <- data.frame(potential_cost)

cost_A <- function(x){policy_A_PV}
cost_B <- function(x){policy_B_PV + x}

cost.compare <- cost.df %>% 
  mutate(cost_a = cost_A(cost.df)) %>% 
  mutate(cost_b = cost_B(cost.df))

ggplot(data = cost.compare) + 
  geom_line(aes(x = potential_cost, y = cost_a), color = "blue") +
  geom_line(aes(x = potential_cost, y = cost_b$potential_cost), color = "red")+
  labs(y = "Total Implementation Cost ($)",
       x = "Potential Additional Cost ($)",
       title = "Comparison of cost of Policy A vs Policy B")
```

